### ISSUE TITLE
Filter for multiple values in an array

### ISSUE THREAD

**Issue by Rhobal** [smart-table/smart-table-filter#2]
Enhancement: Allow to filter for multiple values submitted in an array (e.g. from autofilter list with checkboxes)

Can you take a look at my PR?

**Comment by lorenzofox3** [comment]
I have already commented your PR, please have a look at the review. In my opinion, it is not good to merge yet.

**Comment by lorenzofox3** [comment]
Ah my bad, I had misunderstood the use case. I would rather call the "arrayInclude" to "anyOf". I would also change the typecast function:
- not need for "any": that should be the "default" and if later we want a "lowerCase" type we can introduce it.

**Comment by Rhobal** [comment]
Sorry, I can't see a comment on the PR, but I updated according to your suggestions.

anyOf sounds fine, as does the default typecast. I didn't want to change the default, as it did convert to lower case string and changing might break backwards compatibility. However, `predicate()` uses string as default, so not much harm is done.

**Comment by lorenzofox3** [comment]
Great thanks a lot !

So you could not see the comments (outdated anyway) ?

<img width="746" alt="screen shot 2018-07-23 at 4 54 07 pm" src="https://user-images.githubusercontent.com/2402022/43084628-59ebadbe-8e99-11e8-8afa-afd7e664e702.png">

I must have missed something: I am not familiar with this feature.

Thanks again for your contribution

**Comment by Rhobal** [comment]
Nope no comment to be seen. Maybe because the comments are "Pending"?

I also first thought I could use includes, until I realised that I need to check if value includes input, not the other way round :-). Thanks for merging
